services:
  verzeilberg\UploadImagesBundle\Service\Rotate:
    autowire: true
    autoconfigure: true
    public: false

  app.mailer:
    alias: verzeilberg\UploadImagesBundle\Service\Rotate
    public: true
