services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  verzeilberg\UploadImagesBundle\Service\Rotate:

  verzeilberg\UploadImagesBundle\Metadata\Reader\ImageAnnotationReader:

  upload_images.rotate:
    class: verzeilberg\UploadImagesBundle\Service\Rotate

doctrine:
  orm:
    mappings:
      UploadImagesBundle:
        is_bundle: true
        type: annotation
        dir: 'Entity'
        prefix: 'verzeilberg\UploadImagesBundle\Entity'
        alias: UploadImagesBundle
